### ISSUE TITLE
Mods sync with save fails

### ISSUE THREAD

**Issue by AlatarQ** [circlesabound/fctrl#10]
I just get list cleaned
factorio 2.0.8

**Comment by circlesabound** [comment]
@AlatarQ are you using a save from version 2.0+? I suspect this and #12 are both caused by some change in the format of the save file header

**Comment by AlatarQ** [comment]
yes it's new save from 2.0 version

**Comment by circlesabound** [comment]
Would you mind attaching the save file that's causing this issue so I can reproduce?

**Comment by AlatarQ** [comment]
[alatar02.zip](https://github.com/user-attachments/files/17467664/alatar02.zip)

**Comment by circlesabound** [comment]
Thanks, I can confirm that mods aren't being extracted properly from the save header anymore. You can track the root cause here https://github.com/circlesabound/factorio-file-parser/issues/1
